apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-broker.fullname" . }}
  labels:
    app: {{ template "kafka-broker.name" . }}
    chart: {{ template "kafka-broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 9092
      name: broker
    {{- if .Values.prometheus.jmx.enabled }}
    - port: {{ .Values.prometheus.jmx.port }}
      name: metrics
    {{- end }}
  selector:
    app: {{ template "kafka-broker.name" . }}
    release: {{ .Release.Name }}
