apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafdrop.fullname" . }}
  labels:
    app: {{ template "kafdrop.name" . }}
    chart: {{ template "kafdrop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: {{ .Values.serviceHttpPort }}
  selector:
    app: {{ template "kafdrop.name" . }}
    release: {{ .Release.Name }}
